fix: ensure record names include the domain name
libdns/leaseweb pull request #1
Opened 2024-11-01 14:01 UTC by pimlie

chore: improve error logging

Creating leaseweb dns records was broken, most likely since 16f977f89705fd828c1159e190e33f959760a416 as the fix that was added in 5c5257eb2569593ee6abb0c156b6a9fe92a1c7f5 to append the domain name after the record name was remove in the former commit (by accident I guess?)

Also improved error logging a bit as it was quite difficult at first to understand from the logs what was happening. Now the full error from leaseweb is included in the error message, so f.e. also the specific field errors.

2024-11-01 14:03 UTC, pimlie commented on go.mod
> +go 1.22
fyi: this is required as otherwise line 44 in helpers.go will generate an error `implicit function instantiation requires go1.18 or later`. It doesn't seem required to also update the go.mod version for `caddy-dns/leaseweb`, but it would maybe be nice to make that the same.

2024-11-01 14:05 UTC, pimlie commented
@justinvdk Not sure if you are still the maintainer of this repo and/or still get notifications, so tagging you just in case 🤗

2024-11-02 16:04 UTC, justinvdk requested changes
Hey, Thanks for the contribution. Some context: I am not actively using caddy+leaseweb anymore, so it was not thorough. I did test it with caddy properly this time :). Apologies for any headaces you had for a non-working lib. 

Some minor things that I think will help next time around if there are any changes.

2024-11-02 16:04 UTC, justinvdk commented on helpers.go
> +			recordTTL = supportedTTLs[0]
I agree with the approach, but maybe we could default to 3600 (1 hour) as that is what the web UI of Leaseweb also defaults to.

2024-11-02 16:04 UTC, justinvdk commented on helpers.go
> +		// trimming both zone & domainName is probably overzealous, but better be safe then sorry
For clarity, can we add an example transformation in the comment?
Could be as simple as:
```
// for example: sub.example.org -> sub.example.org.
```

or whatever is a correct example.

2024-11-02 16:04 UTC, justinvdk commented on go.mod
> +go 1.22
Yeah, thats ok. I was able to build it just fine with 1.23

2024-11-02 16:07 UTC, pimlie commented on helpers.go
> +			recordTTL = supportedTTLs[0]
Couldn't a long TTL potentially cause problems with DNS-01 challenges? My reasoning for the lowest possible value was that this lib will probably mostly be used to solve ACME DNS-01 challenges and in that case a lower TTL is preferred so record changes are propagated as quickly as possible...

2024-11-02 16:13 UTC, pimlie commented on helpers.go
> +		// trimming both zone & domainName is probably overzealous, but better be safe then sorry
done

2024-11-02 16:15 UTC, pimlie commented on helpers.go
> +			recordTTL = supportedTTLs[0]
Added a code comment with that explanation :)

2024-11-02 16:19 UTC, justinvdk commented on helpers.go
> +			recordTTL = supportedTTLs[0]
Hey, you're right. I was just thinking pure DNS but it makes sense to keep it low of course!

2024-11-02 16:24 UTC, merged